"""Refuse to ship evidence that is older than the code that produced it.

Every file in ``results/`` is a claim, and each one was generated by running
something at a moment in time. Change the simulator or the policy gate and the
claim silently stops describing the system — the file does not complain, the
tests still pass, and the README goes on linking to it as current.

That is not hypothetical. On 2026-08-25 three of seven were stale:
``calibration.md`` and ``model_bakeoff.md`` predated the resolved-history layer
entirely, and ``sensitivity.md`` predated a policy rule that changed what the
gate allows. All three were linked from the README as evidence.

Freshness is judged by git, not by mtime: a checkout gives every file the same
timestamp, so "when was this file last committed" against "when was its input
last committed" is the only comparison that survives cloning the repository.

**This is a hint, not a verdict, and it exits 0 unless given ``--strict``.**
An artifact that regenerates to identical bytes after a code change is not
re-committed — git records no change — so it keeps its older date and gets
flagged here while being perfectly current. That happened on the first run:
three of the six it named turned out to reproduce byte-for-byte, meaning the
change had not touched them at all.

The authoritative check is ``make verify-evidence``, which regenerates
everything and fails only if a byte actually differs. Timestamps are a cheap
proxy for a question that can simply be answered, so use them to decide *when*
to run the real thing, never as the answer itself.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

# Each artifact, and the paths whose changes invalidate it.
DEPENDS: dict[str, tuple[str, ...]] = {
    "results/report.md": ("src/wapas", "sim", "eval/run_batch.py", "policies"),
    "results/report-rules.md": ("src/wapas", "sim", "eval/run_batch.py", "policies"),
    "results/summary.json": ("src/wapas", "sim", "eval/run_batch.py", "policies"),
    "results/dashboard.html": ("dashboard/build.py", "results/summary.json"),
    "results/calibration.md": ("src/wapas", "sim", "eval/calibrate.py", "eval/stats.py"),
    "results/sensitivity.md": ("src/wapas", "sim", "eval/sensitivity.py", "policies"),
    "results/redteam.md": ("src/wapas", "redteam", "policies"),
    "results/triage.md": ("src/wapas", "sim", "eval/triage_study.py", "policies"),
    # The bake-off selects a model rather than measuring the system, so it is
    # allowed to be older — but not silently. It is listed so a reader is told.
    "results/model_bakeoff.md": ("src/wapas/diagnose", "sim/signals.py"),
}

ADVISORY = {"results/model_bakeoff.md"}
"""Reported, but does not fail the build. Selection evidence ages differently
from measurement evidence: the choice of model stands even when the numbers
behind it were taken on an earlier world, so long as nobody pretends
otherwise."""


def last_commit(path: str) -> int:
    out = subprocess.run(
        ["git", "log", "-1", "--format=%ct", "--", path],
        capture_output=True, text=True, check=False,
    ).stdout.strip()
    return int(out) if out else 0


def main() -> int:
    strict = "--strict" in sys.argv
    stale: list[str] = []
    advisory: list[str] = []

    for artifact, inputs in DEPENDS.items():
        if not Path(artifact).exists():
            stale.append(f"{artifact} does not exist")
            continue
        generated = last_commit(artifact)
        for source in inputs:
            changed = last_commit(source)
            if changed > generated:
                line = (f"{artifact} was last generated before {source} changed "
                        f"({_ago(generated)} vs {_ago(changed)})")
                (advisory if artifact in ADVISORY else stale).append(line)
                break

    for line in advisory:
        print(f"note: {line}", file=sys.stderr)

    if stale:
        print("\nPossibly stale — regenerate to find out:", file=sys.stderr)
        for line in stale:
            print(f"  {line}", file=sys.stderr)
        print("\n  make verify-evidence   # regenerates and fails only on a real diff",
              file=sys.stderr)
        return 1 if strict else 0

    print(f"all {len(DEPENDS)} evidence files are newer than their inputs")
    return 0


def _ago(stamp: int) -> str:
    import datetime as _dt

    if not stamp:
        return "never committed"
    return _dt.datetime.fromtimestamp(stamp, tz=_dt.UTC).strftime("%Y-%m-%d %H:%M")


if __name__ == "__main__":
    raise SystemExit(main())
